// EDITABLE CONTENT: update personal details, project descriptions, URLs, and email here.
window.PORTFOLIO = {
  person: { name: "Mohamed Hassan Elsayed", email: "", github: "", linkedin: "" },
  projects: {
    studio: { number:"CASE STUDY / 01", title:"StudioPortfolio", overview:"A photography studio portfolio and content-management project. This entry is an editable summary; add verified details and screenshots before publishing.", problem:"[Describe the real user or studio need this project addresses.]", approach:"[Add your implementation approach and confirmed technical decisions.]", architecture:"[Add architecture/data flow only if documented and accurate.]", features:["Portfolio presentation","Content management","[Add confirmed feature]"], tools:["ASP.NET Core MVC","Entity Framework Core","SQL Server","JavaScript"], media:"[Replace this preview with an actual project screenshot or demo image.]", github:"", demo:"" },
    wood: { number:"CASE STUDY / 02", title:"WoodTradeERP", overview:"An ERP concept for wood trading and workshop operations. A practice project exploring how operational workflows can be represented in software.", problem:"[Describe the workflow and problem this concept addresses.]", approach:"[Add the actual design and implementation decisions.]", architecture:"[Add only the architecture and data flow you implemented.]", features:["[Add verified workflow or module]","[Add verified feature]"], tools:["ASP.NET Core MVC",".NET 8","Entity Framework Core","SQL Server"], media:"[Replace with a real screenshot when available.]", github:"", demo:"" },
    api: { number:"CASE STUDY / 03", title:"E-Commerce API", overview:"A learning project focused on ASP.NET Core APIs and Clean Architecture. Add the exact scope and implementation details before sharing.", problem:"[Describe the learning goal or application need.]", approach:"[Add the real technical decisions and trade-offs.]", architecture:"[Document the layers and request/data flow you actually built.]", features:["REST API endpoints","[Add verified feature]"], tools:["ASP.NET Core Web API","Clean Architecture","Entity Framework Core","SQL Server"], media:"[Replace with a real screenshot or API documentation image.]", github:"", demo:"" }
  },
  capabilities: {
    backend:{title:"Backend",desc:"Building application logic and web endpoints that connect user needs with reliable data operations.",skills:["C#","ASP.NET Core MVC","ASP.NET Core Web API"],project:"StudioPortfolio · WoodTradeERP · E-Commerce API"},
    data:{title:"Data",desc:"Working with relational data, querying it, and mapping application needs to persistence.",skills:["Entity Framework Core","LINQ","SQL Server"],project:"StudioPortfolio · WoodTradeERP · E-Commerce API"},
    frontend:{title:"Frontend",desc:"Creating responsive interfaces and connecting user interactions to application behavior.",skills:["HTML","CSS","JavaScript","Bootstrap","Angular"],project:"StudioPortfolio · [Add Angular project if applicable]"},
    engineering:{title:"Engineering",desc:"Applying core programming practices and common web application patterns.",skills:["OOP","REST APIs","Authentication & Authorization","Clean Architecture","Git / GitHub"],project:"StudioPortfolio · WoodTradeERP · E-Commerce API"}
  }
};